0.0.2
- Run the script directly via systemd
- Small formatting and shellcheck linting fixes

diff --git a/adjust-pci-latency b/adjust-pci-latency
--- a/adjust-pci-latency
+++ b/adjust-pci-latency
@@ -2,7 +2,7 @@
 
 # The GPLv2 License
 #
-#   Copyright (C) 2024  pyamsoft
+#   Copyright (C) 2025 pyamsoft
 #
 #   This program is free software; you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
@@ -21,8 +21,9 @@
 # adjust-pci-latency
 # by: pyamsoft <developer(dot)pyamsoft(at)gmail(dot)com>
 
-readonly NAME="$(basename "$0")"
-readonly VERSION="0.0.1"
+NAME="$(basename "$0")"
+readonly VERSION="0.0.2"
+readonly NAME
 
 # Taken from, with modification
 # https://github.com/CachyOS/CachyOS-Settings/blob/master/usr/bin/pci-latency
@@ -86,7 +87,8 @@ _tweak_pci_audio() {
 }
 
 _usage() {
-  printf -- '%s\n' "$(cat <<EOF
+  printf -- '%s\n' "$(
+    cat <<EOF
 ${NAME} ${VERSION}
 
 usage: ${NAME} <mode>
@@ -104,7 +106,7 @@ pro-audio     Adjust system PCI latency to maximize the PCI latency timer
               of PCI sound card devices for audio production.
 
 EOF
-)"
+  )"
 }
 
 ##
@@ -121,34 +123,34 @@ main() {
   fi
 
   case "$1" in
-    game|games|gaming)
-      # Check if the script is run with root privileges
-      if [ "$(id -u)" -ne 0 ]; then
-        printf -- 'Error: This script must be run with root privileges.\n'
-        return 1
-      fi
+  game | games | gaming)
+    # Check if the script is run with root privileges
+    if [ "$(id -u)" -ne 0 ]; then
+      printf -- 'Error: This script must be run with root privileges.\n'
+      return 1
+    fi
 
-      _tweak_pci_gaming || {
-        printf -- 'Failed to adjust PCI latency for gaming.\n'
-        return 4
-      }
-      ;;
-    audio|proaudio|pro-audio)
-      # Check if the script is run with root privileges
-      if [ "$(id -u)" -ne 0 ]; then
-        printf -- 'Error: This script must be run with root privileges.\n'
-        return 1
-      fi
+    _tweak_pci_gaming || {
+      printf -- 'Failed to adjust PCI latency for gaming.\n'
+      return 4
+    }
+    ;;
+  audio | proaudio | pro-audio)
+    # Check if the script is run with root privileges
+    if [ "$(id -u)" -ne 0 ]; then
+      printf -- 'Error: This script must be run with root privileges.\n'
+      return 1
+    fi
 
-      _tweak_pci_audio || {
-        printf -- 'Failed to adjust PCI latency for pro-audio.\n'
-        return 4
-      }
-      ;;
-    *)
-      _usage || return 3
-      return 3
-      ;;
+    _tweak_pci_audio || {
+      printf -- 'Failed to adjust PCI latency for pro-audio.\n'
+      return 4
+    }
+    ;;
+  *)
+    _usage || return 3
+    return 3
+    ;;
   esac
 
   return 0
